### ISSUE TITLE
Error messages?

### ISSUE THREAD

**Issue by dcplebranch** [a-digital/eventbrite#13]
If there is an error pulling up events, where can I see the error message? I implemented the site a while ago, and this plugin worked fine then. However, now it is not pulling in any events. If there is some kind of error, I want to be able to check what the error is so I can start fixing the problem.

Thanks,

**Comment by mark-adigital** [comment]
Hi @dcplebranch  - was this related to #14 in the end?

**Comment by dcplebranch** [comment]
No, it was actually an issue with the Auth token. We figured it out for that particular instance, but it would still be nice to have some place to see all the API errors in case something went wrong in the future. Thanks.

**Comment by mark-adigital** [comment]
Ok, we're obviously also having the chat over in #11 about suppressing errors which is a little at odds with this. I never released the update to only show the error text because I was about to be off for a week and wasn't sure if there might be more updates to make, having only just done a release. I could release that now and then you should be able to see the errors in browser outside of production for fixing, and have them suppressed on live.
