### ISSUE TITLE
Craft search

### ISSUE THREAD

**Issue by watchwood** [a-digital/eventbrite#9]
Does this plugin integrate into Craft's search feature?  If not, can you upgrade it so that eventbrite events can be searched as part of the Craft search tool?

**Comment by mark-adigital** [comment]
Hi,

Thanks for your interest!

Due to the way the plugin has been built and some restrictions on the API, this feature would be tricky to implement. The plugin stores nothing in Craft, everything is read from Eventbrite's API (though I do recommend caching calls to the plugin for this reason), so there's no data in Craft itself to search natively.

There used to be an API call that enabled event searching from Eventbrite which could have helped, but [unfortunately it's now become deprecated](https://www.eventbrite.com/platform/api#/reference/event-search). There's more info about why this happened in [the changelog](https://www.eventbrite.com/platform/docs/changelog).

The changelog also recommends searching by venue, organisation, or specific event ID instead. The plugin already has methods to retrieve events and venues on this basis, so right now the best I could suggest would be to maybe have a separate event search which works mainly by selecting a venue (as I don't think picking from one organisation or a list of numeric IDs would offer much value). Or with the right UI and twig logic in your search results, you could look to build something like that into your general search form too.

Sorry I can't be more helpful - it's a pain the search API method has been withdrawn as I had intended to build that in at some stage, and to read the data into Craft would be a pretty huge refactor and change of approach. Hopefully a version of the functionality through the API is restored at some point.

Hope that helps, happy to discuss further if you wish.

Thanks,

Mark

**Comment by mark-adigital** [comment]
Closing due to lack of further feedback.
